### ISSUE TITLE
help

### ISSUE THREAD

**Issue by tl123987** [HaohuaLv/OpenCV4.7_MinGW_build_with_contrib#1]
Can you help me?
![image](https://github.com/HaohuaLv/OpenCV4.7_MinGW_build_with_contrib/assets/65206700/2625004d-701a-403b-b4c7-f7087d50c1fb)
I encountered this problem after successfully compiling, but I have already added the library to the environment variable.

thansk

**Comment by HaohuaLv** [comment]
Can you show your environment variable PATH?

**Comment by tl123987** [comment]
![image](https://github.com/HaohuaLv/OpenCV4.7_MinGW_build_with_contrib/assets/65206700/3a158078-bb28-4fd9-b73f-984ad4372ead)
![image](https://github.com/HaohuaLv/OpenCV4.7_MinGW_build_with_contrib/assets/65206700/53b97614-93fb-4bb0-a3fd-a8ade91af2d7)
I have tried many versions, all of which can be compiled successfully but cannot run.

**Comment by HaohuaLv** [comment]
你试试看按照这个方法行不行？
https://github.com/huihut/OpenCV-MinGW-Build/issues/18
我是编译完配置好直接就成功的

**Comment by tl123987** [comment]
我试了好像还是不行

**Comment by HaohuaLv** [comment]
![1693791552289](https://github.com/HaohuaLv/OpenCV4.7_MinGW_build_with_contrib/assets/81418362/1cf7dea0-3d70-42d0-a448-cfd06047cf87)
![1693791607790](https://github.com/HaohuaLv/OpenCV4.7_MinGW_build_with_contrib/assets/81418362/ae0c6475-1ebf-4b91-b8db-383219e5359b)
![1693791662077](https://github.com/HaohuaLv/OpenCV4.7_MinGW_build_with_contrib/assets/81418362/6a89746e-8978-4f96-9549-3993aea4c202)
那我也没啥办法了，配置opencv有点有点久远了，要不你参考下我的配置看看有什么问题？我是在vscode上配置的

**Comment by tl123987** [comment]
这个使用必须与mingw版本匹配吗

**Comment by HaohuaLv** [comment]
应该只要比我这个版本高就没问题，低版本有可能会有问题，你可以试下装个新版本的mingw

**Comment by tl123987** [comment]
我安装的最新的，不知道是什么原因，放弃了，谢谢你了

**Comment by tl123987** [comment]
我安装了你的mingw版本，竟然成功了。看来得要对应版本，最新版的不能用，为什么你们编译都用8 ，现在13不都出来了吗
